[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpa-calculator-baset"
version = "0.0.1"
authors = [
  { name="Abdalbaset Taher", email="ataher@msudenver.edu" },
]
description = "Credit-weighted GPA calculator"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Barlos1233/26FCS3250-002-prj-1"

[tool.hatch.build.targets.wheel]
packages = ["gpa_calculator"]

[tool.hatch.build.targets.sdist]
include = ["gpa_calculator", "README.md", "pyproject.toml"]